# Dockerfile.dev
FROM node:18

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY tsconfig.json ./
COPY nodemon.json ./
COPY src ./src

RUN npm install -g nodemon typescript ts-node

EXPOSE 3000
CMD ["nodemon"]